/*
 * Created on 8 Dec 2015 ( Time 12:48:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.jcodeshare.webtemplate.data.model;

import java.util.List;
import java.util.ArrayList;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "location")
public class Location {

    //private static final long serialVersionUID = 1L;
    
    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Access(AccessType.PROPERTY)
    @Id @GeneratedValue
    @Column(name = "id", unique=true, nullable=false)
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "city")
    private String city;

    @Column(name = "longitude")
    private float longitude;
    
    @Column(name = "latitude")
    private float latitude;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setLatitude( float latitude ) {
        this.latitude = latitude;
    }
    
    public float getLatitude() {
        return this.latitude;
    }    

    public void setLongitude( float longitude ) {
        this.longitude = longitude;
    }
    
    public float getLongitude() {
        return this.longitude;
    } 

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(longitude);
        sb.append("|");
        sb.append(latitude);
        return sb.toString(); 
    } 


}
