/*
 * Created on 8 Dec 2015 ( Time 12:48:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.jcodeshare.webtemplate.data.model;

import java.util.List;
import java.util.ArrayList;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumns;
import javax.persistence.JoinColumn;
import javax.persistence.UniqueConstraint;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.ElementCollection;

import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Cascade;
import org.springframework.beans.factory.annotation.Autowired;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.jcodeshare.webtemplate.data.model.Comments;

@Entity
@Table(name = "users")
public class Users {

    //private static final long serialVersionUID = 1L;
    
    // 2 values means in the future we can have a static webtemplate data type reference
    // and still meaningfully trace where information is relevant 
    public final static int ANONYMOUS_USER_ID = 1;
    public final static int DEFAULT_USER_ID = ANONYMOUS_USER_ID;
    public final static String ANONYMOUS_USERNAME = "ANONYMOUS";
    public final static String DEFAULT_USERNAME = ANONYMOUS_USERNAME;
    public final static List<Comments> DEFAULT_EMPTY_LIST = new ArrayList<Comments>(0);

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Access(AccessType.PROPERTY)
    @Id @GeneratedValue
    @Column(name = "id", unique=true, nullable=false)
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "username", nullable=false)
    private String username;

    @Column(name = "password", nullable=false)
    private String password;

    @OneToMany(targetEntity=Comments.class, mappedBy="user", fetch=FetchType.LAZY)
    @Cascade(CascadeType.REMOVE)
    @ElementCollection(targetClass=Comments.class)
    @JsonManagedReference
    private List<Comments> comments;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    public List<Comments> getComments() {
        return this.comments;
    }

    public void setComments(List<Comments> coments) {
        this.comments = comments;
    }



    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 


}
