/*
 * Created on 8 Dec 2015 ( Time 12:48:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.jcodeshare.webtemplate.data.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "users")
public class Users {

    //private static final long serialVersionUID = 1L;
    
    // 2 values means in the future we can have a static webtemplate data type reference
    // and still meaningfully trace where information is relevant 
    public final static int ANONYMOUS_USER_ID = 1;
    public final static int DEFAULT_USER_ID = ANONYMOUS_USER_ID;
    public final static String ANONYMOUS_USERNAME = "ANONYMOUS";
    public final static String DEFAULT_USERNAME = ANONYMOUS_USERNAME;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id @GeneratedValue
    @Column(name = "id", nullable=false)
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "username", nullable=false)
    private String username;

    @Column(name = "password", nullable=false)
    private String password;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 


}
